<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Template.Master" CodeBehind="ViewCart.aspx.vb" Inherits="OnlineStore.ViewCart" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <!-- version1 (just for checking) -->
<%--    <asp:SqlDataSource ID="SqlDSCart1" runat="server"
        DataSourceMode="DataSet"
        ConnectionString="<%$ ConnectionStrings:ConnectionStringOnlineStore %>"
        SelectCommand=""
        DeleteCommand="DELETE FROM [Cart] WHERE ([CartNo] = @CartNo AND [ProductNo] = @ProductNo)"
        UpdateCommand="UPDATE [Cart] SET [Quantity] = @Quantity WHERE ([CartNo] = @CartNo AND [ProductNo] = @ProductNo)"></asp:SqlDataSource>
    <asp:GridView ID="gvCart" runat="server" AutoGenerateColumns="False"
        DataSourceID="SqlDSCart1" AllowPaging="True" PageSize="3" DataKeyNames="CartNo,ProductNo"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
        EmptyDataText="There are no products in the cart.">
        <Columns>
            <asp:BoundField DataField="ProductNo" HeaderText="Product No" InsertVisible="False" ReadOnly="true"
                SortExpression="Product No" />
            <asp:BoundField DataField="ProductName" HeaderText="Product Name" InsertVisible="False" ReadOnly="true"
                SortExpression="Product Name" />
            <asp:BoundField DataField="Quantity" HeaderText="Quantity"
                SortExpression="Quantity" />
            <asp:TemplateField>
                <ItemTemplate>
                    <asp:Label ID="TotalLabel" runat="server" Text='<%# Eval("Quantity")%>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="ProductPrice" HeaderText="Price" SortExpression="Price" InsertVisible="False" ReadOnly="true" />
        </Columns>
    </asp:GridView>--%>

    <!-- version2 (HTML template) -->
    <div style="float: right; margin: 0 30px 5px 0;">
        <asp:Button ID="btnEmptyCart" runat="server" Text="Empty the Cart" />
    </div>   
    <asp:SqlDataSource ID="sqlDSCart1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ConnectionStringOnlineStore %>"> 
    </asp:SqlDataSource>
    <asp:ListView ID="lvCart" runat="server" DataSourceID="sqlDSCart1"
            OnItemCommand="lvCart_OnItemCommand" CellPadding="3" DataKeyField="CartNo"
            CellSpacing="0" RepeatColumns="1" DataKeyNames="CartID">
        <LayoutTemplate>              
            <div style="float: right; margin: 0 30px 5px 0;">
                <asp:Label ID="lblPage" runat="server" Text="" Font-Size="14px"></asp:Label>
            </div><br />
            <div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu" style="background-color: orangered;">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						<asp:PlaceHolder runat="server" id="itemPlaceholder"></asp:PlaceHolder>
					</tbody>
				</table> 
            </div>
        </LayoutTemplate>
        <ItemTemplate>
            <tr>
				<td class="cart_product">
                    <!-- TO LINK TO PRODUCTDETAIL PAGE, PRODUCTID MUST BE ADDED TO THE CART TABLE IN DB -->
                    <%--<a href="ProductDetail.aspx?ProductID=<%# Eval("ProductID") %>"><img src="img/<%# Trim(Eval("ProductNo")) %>.jpg" alt="" width="320" height="180"></a>--%>
					<a href=""><img src="img/<%# Trim(Eval("ProductNo")) %>.jpg" alt="" width="320" height="180"></a>
				</td>
				<td class="cart_description">
					<h4><a href=""><%# Trim(Eval("ProductName")) %></a></h4>
					<p>Product Number: <%# Eval("ProductNo") %></p>
				</td>
				<td class="cart_price">
					<p>$<%# Eval("ProductPrice") %></p>
				</td>
				<td class="cart_quantity">
                    <asp:TextBox ID="tbQuantity" Text='<%# Eval("Quantity")%>' Width="50px" CssClass="" runat="server"></asp:TextBox>
                    <asp:LinkButton runat="server" ID="lbUpdate" Text='Update'
                        CommandName="cmdUpdate" CommandArgument='<%# Eval("ProductNo")%>' />
                    <asp:LinkButton runat="server" ID="lbDelete" Text='Delete'
                        CommandName="cmdDelete" CommandArgument='<%# Eval("ProductNo")%>' />
				</td>
				<td class="cart_total">
					<p class="cart_total_price">$</p>
				</td>
				<td class="cart_delete">
					
				</td>
            </tr> 
        </ItemTemplate>
    </asp:ListView>

</asp:Content>
